services:
  - type: web
    name: music-downloader-bot
    runtime: python
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    pythonVersion: 3.11.8
